/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bannedbook_app_service_NativeCall */

#ifndef _Included_org_bannedbook_app_service_NativeCall
#define _Included_org_bannedbook_app_service_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bannedbook_app_service_NativeCall
 * Method:    execPolipo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bannedbook_app_service_NativeCall_execPolipo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
