#!/usr/bin/env bash

#
# Generate graph from collision test data (requires ploticus).
# See top Makefile target 'collision_test' for details.
#
# Invocation:
#
# ./dograph DATAFILE
#

zcat $1 > uncompressed
ploticus -prefab lines data=uncompressed x=1 y=5 -maxfields 8000000 -maxrows 1000000 -maxvector 1000000 pointsym=none -png -o $1.png
rm -f uncompressed
