#define CAVL_PARAM_NAME SAvl__Tree
#define CAVL_PARAM_FEATURE_COUNTS SAVL_PARAM_FEATURE_COUNTS
#define CAVL_PARAM_FEATURE_KEYS_ARE_INDICES 0
#define CAVL_PARAM_FEATURE_NOKEYS SAVL_PARAM_FEATURE_NOKEYS
#define CAVL_PARAM_TYPE_ENTRY SAvlEntry
#define CAVL_PARAM_TYPE_LINK SAvl__TreeLink
#define CAVL_PARAM_TYPE_KEY SAvlKey
#define CAVL_PARAM_TYPE_ARG SAvlArg
#define CAVL_PARAM_TYPE_COUNT SAvlCount
#define CAVL_PARAM_VALUE_COUNT_MAX SAVL_PARAM_VALUE_COUNT_MAX
#define CAVL_PARAM_VALUE_NULL ((SAvl__TreeLink)NULL)
#define CAVL_PARAM_FUN_DEREF(arg, link) (link)
#define CAVL_PARAM_FUN_COMPARE_ENTRIES(arg, entry1, entry2) SAVL_PARAM_FUN_COMPARE_ENTRIES((arg), (entry1).link, (entry2).link)
#define CAVL_PARAM_FUN_COMPARE_KEY_ENTRY(arg, key1, entry2) SAVL_PARAM_FUN_COMPARE_KEY_ENTRY((arg), (key1), (entry2).link)
#define CAVL_PARAM_MEMBER_CHILD SAVL_PARAM_MEMBER_NODE . child
#define CAVL_PARAM_MEMBER_BALANCE SAVL_PARAM_MEMBER_NODE . balance
#define CAVL_PARAM_MEMBER_PARENT SAVL_PARAM_MEMBER_NODE . parent
#define CAVL_PARAM_MEMBER_COUNT SAVL_PARAM_MEMBER_NODE . count
