package com.nononsenseapps.feeder.ui.compose.theme

import androidx.compose.ui.graphics.Color

val Green700 = Color(0xff0b8043)

val md_theme_light_primary = Color(0xFF006D37)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF93F8AE)
val md_theme_light_onPrimaryContainer = Color(0xFF00210C)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E8D3)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1F12)
val md_theme_light_tertiary = Color(0xFF3A656E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDEAF5)
val md_theme_light_onTertiaryContainer = Color(0xFF001F25)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF7)
val md_theme_light_onBackground = Color(0xFF191C19)
val md_theme_light_surface = Color(0xFFFBFDF7)
val md_theme_light_onSurface = Color(0xFF191C19)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF77DB93)
val md_theme_light_surfaceTint = Color(0xFF006D37)

val md_theme_eink_primary = Color(0xFF000000)
val md_theme_eink_onPrimary = Color(0xFFFFFFFF)
val md_theme_eink_primaryContainer = Color(0xFFFFFFFF)
val md_theme_eink_onPrimaryContainer = Color(0xFF000000)
val md_theme_eink_secondary = Color(0xFF000000)
val md_theme_eink_onSecondary = Color(0xFFFFFFFF)
val md_theme_eink_secondaryContainer = Color(0xFFFFFFFF)
val md_theme_eink_onSecondaryContainer = Color(0xFF000000)
val md_theme_eink_tertiary = Color(0xFF000000)
val md_theme_eink_onTertiary = Color(0xFFFFFFFF)
val md_theme_eink_tertiaryContainer = Color(0xFFFFFFFF)
val md_theme_eink_onTertiaryContainer = Color(0xFF000000)
val md_theme_eink_error = Color(0xFF000000)
val md_theme_eink_errorContainer = Color(0xFFFFFFFF)
val md_theme_eink_onError = Color(0xFFFFFFFF)
val md_theme_eink_onErrorContainer = Color(0xFF000000)
val md_theme_eink_background = Color(0xFFFFFFFF)
val md_theme_eink_onBackground = Color(0xFF000000)
val md_theme_eink_surface = Color(0xFFFFFFFF)
val md_theme_eink_onSurface = Color(0xFF000000)
val md_theme_eink_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_eink_onSurfaceVariant = Color(0xFF000000)
val md_theme_eink_outline = Color(0xFF717971)
val md_theme_eink_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_eink_inverseSurface = Color(0xFF2E312E)
val md_theme_eink_inversePrimary = Color(0xFFFFFFFF)
val md_theme_eink_surfaceTint = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF77DB93)
val md_theme_dark_onPrimary = Color(0xFF00391A)
val md_theme_dark_primaryContainer = Color(0xFF005228)
val md_theme_dark_onPrimaryContainer = Color(0xFF93F8AE)
val md_theme_dark_secondary = Color(0xFFB7CCB8)
val md_theme_dark_onSecondary = Color(0xFF223526)
val md_theme_dark_secondaryContainer = Color(0xFF384B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E8D3)
val md_theme_dark_tertiary = Color(0xFFA2CED9)
val md_theme_dark_onTertiary = Color(0xFF01363F)
val md_theme_dark_tertiaryContainer = Color(0xFF204D56)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEAF5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C19)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C19)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)
val md_theme_dark_inverseOnSurface = Color(0xFF191C19)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D37)
val md_theme_dark_surfaceTint = Color(0xFF77DB93)

val seed = Green700

val NavBarScrimLight = Color(0xE3ffffff)
val NavBarScrimDark = Color(0xC3000000)

val SwipingItemToReadColor = Color(0xffff5252)
val SwipingItemToUnreadColor = Color(0xff1C9255)
